config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  authenticate :user do
    get 'users/index'
    get 'users/match/:user_id' => 'users#match', as: :match
    resources :teams
    resources :nationalities
    resources :leagues
    resources :clubs
    resources :roles
    resources :players do
      get 'sell', on: :member
      get 'my/players', action: :my_players, as: :my, on: :collection
    end
    resources :packs do
      get 'list', on: :collection
      get ':user_id/buy', action: :buy, as: :buy, on: :member
    end
  end
end

app/models/pack.rb
class Pack < ApplicationRecord
  has_and_belongs_to_many :players

  def buy(user)
    amount = user.credit - self.price
    if amount < 0
      return false
    end

    user.credit = amount
    user.save
  end

  def open
    available_players = self.players
    players_list = []
    for player in available_players do
      increment = 0
      while increment < (100 - player.rarity) do
        players_list.push(player.id)
        increment += 1
      end
    end
    players_list = players_list.shuffle

    pack_players = []
    increment = 0
    while increment < self.cards_number do
      pack_players.push(Player.find(players_list.sample))
      increment += 1
    end

    pack_players
  end
end

app/controllers/packs_controller.rb
class PacksController < ApplicationController
  before_action :set_pack, only: [:show, :edit, :update, :destroy]

  # GET /packs
  def index
    @packs = Pack.all
  end

  def list
    @packs = Pack.all
    @isBuy = true

    render 'index'
  end

  def buy
    @pack = Pack.find(params[:id])
    @user = User.find(params[:user_id])
    success = @pack.buy(@user)
    if success
      @pack_players = @pack.open
      for player in @pack_players do
        @user.players << player
      end
    end

    respond_to do |format|
      if success
        format.html { render :buy, notice: 'La pack a bien été acheté.' }
      else
        format.html { redirect_to list_packs_path, notice: 'Vous ne pouvez pas acheter ce pack.' }
      end
    end
  end

  # GET /packs/1
  def show
    @pack = Pack.find(params[:id])
    @players = @pack.players

    respond_to do |format|
      format.html
    end
  end

  # GET /packs/new
  def new
    @pack = Pack.new
    @players = Player.all
  end

  # GET /packs/1/edit
  def edit
    @players = Player.all
  end

  # POST /packs
  def create
    @pack = Pack.new(pack_params)

    respond_to do |format|
      if @pack.save
        format.html { redirect_to @pack, notice: 'Pack was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /packs/1
  def update
    params[:pack][:player_ids] ||= []
    @pack = Pack.find(params[:id])

    respond_to do |format|
      if @pack.update(pack_params)
        format.html { redirect_to @pack, notice: 'Pack was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /packs/1
  def destroy
    @pack.destroy
    respond_to do |format|
      format.html { redirect_to packs_url, notice: 'Pack was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pack
      @pack = Pack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pack_params
      params.require(:pack).permit(:name, :price, :cards_number, :player_ids => [])
    end
end

app/helpers/packs_helper.rb
module PacksHelper
end

app/views/packs/_form.html.erb
<%= form_with(model: pack, local: true) do |form| %>
  <% if pack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pack.errors.count, "error") %> prohibited this pack from being saved:</h2>

      <ul>
      <% pack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :cards_number %>
    <%= form.number_field :cards_number %>
  </div>

  <% @players.each do |player| %>
    <div>
      <%= check_box_tag "pack[player_ids][]", player.id, @pack.players.include?(player) %>
      <%= player.name %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/packs/buy.html.erb
<p id="notice"><%= notice %></p>

<p>Félicitations vous venez d'obtenir les joueurs suivants</p>

<% @pack_players.each do |player| %>
  <div>
    <%= player.name %>
  </div>
<% end %>

app/views/packs/edit.html.erb
<h1>Modifier Pack</h1>

<%= render 'form', pack: @pack %>

<%= link_to 'Afficher', @pack, class: 'btn btn-primary mr-3 mt-3' %>
<%= link_to 'Retour', packs_path, class: 'btn btn-light mt-3' %>

app/views/packs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Les Packs</h1>

<table class="table text-center">
  <thead>
    <tr>
      <th scope="col">Nom</th>
      <th scope="col">Prix</th>
      <th scope="col" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @packs.each do |pack| %>
      <tr>
        <td><%= image_tag 'Packs/pack-default.png', width: "70", alt: 'Pack preview' %></td>
        <td><%= pack.name %></td>
        <td><%= pack.price %></td>
        <% if current_user.try(:admin?) && !@isBuy %>
          <td><%= link_to 'Afficher', pack, class: 'btn btn-primary' %></td>
          <td><%= link_to 'Modifier', edit_pack_path(pack), class: 'btn btn-warning' %></td>
          <td><%= link_to 'Supprimer', pack, method: :delete, data: { confirm: 'Êtes-vous sûr?' }, class: 'btn btn-danger' %></td>
        <% end %>
        <% if user_signed_in? && @isBuy %>
          <td><%= link_to 'Acheter', buy_pack_path(pack, current_user), class: 'btn btn-light' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouveau Pack', new_pack_path, class: 'btn btn-success mb-3 ml-3' %>

app/views/packs/new.html.erb
<h1>Nouveau Pack</h1>

<%= render 'form', pack: @pack %>

<%= link_to 'Retour', packs_path, class: 'btn btn-light mt-3' %>

app/views/packs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @pack.name %>
</p>

<p>
  <strong>Prix:</strong>
  <%= @pack.price %>
</p>

<% @players.each do |player| %>
  <div>
    <%= player.name %>
  </div>
<% end %>

<%= link_to 'Modifier', edit_pack_path(@pack), class: 'btn btn-warning mr-3' %>
<%= link_to 'Retour', packs_path, class: 'btn btn-light' %>