config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  authenticate :user do
    get 'users/index'
    get 'users/match/:user_id' => 'users#match', as: :match
    resources :teams
    resources :nationalities
    resources :leagues
    resources :clubs
    resources :roles
    resources :players do
      get 'sell', on: :member
      get 'my/players', action: :my_players, as: :my, on: :collection
    end
    resources :packs do
      get 'list', on: :collection
      get ':user_id/buy', action: :buy, as: :buy, on: :member
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_and_belongs_to_many :packs
  has_and_belongs_to_many :teams
  belongs_to :club
  belongs_to :nationality
  belongs_to :role
  has_one_attached :avatar

  def sell(user)
    # remove the player from association table
    sql = "DELETE FROM players_users WHERE user_id=#{user.id} AND player_id=#{self.id} LIMIT 1"
    ActiveRecord::Base.connection.execute(sql)

    user.credit = user.credit + self.price
    user.save
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy, :sell]

  def index
    @players = Player.all
  end

  def my_players
    @players = current_user.players
  end

  def show
  end

  def sell
    @player.sell(current_user)

    redirect_to my_players_url, notice: "#{@player.name} a bien été vendu"
  end

  def new
    @player = Player.new
  end

  def edit; end

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to @player, notice: 'Player was successfully created.'
    else
      render :new
    end
  end

  def update
    if @player.update(player_params)
      redirect_to @player, notice: 'Player was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @player.destroy
    redirect_to players_url, notice: 'Player was successfully destroyed.'
  end

  private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:name, :speed, :strength, :defense, :shoot, :rarity, :avatar, :note, :price, :role_id, :club_id, :nationality_id)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label 'Prix de vente' %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.number_field :note %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.number_field :speed %>
  </div>

  <div class="field">
    <%= form.label :strength %>
    <%= form.number_field :strength %>
  </div>

  <div class="field">
    <%= form.label :defense %>
    <%= form.number_field :defense %>
  </div>

  <div class="field">
    <%= form.label :shoot %>
    <%= form.number_field :shoot %>
  </div>

  <div class="field">
    <%= form.label :rarity %>
    <%= form.number_field :rarity %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
    <% if @player.avatar.attached? %>
      <p>
        <strong>Image actuelle :</strong>
        <%= image_tag @player.avatar, width: '100' %>
      </p>
    <% else %>
      <p>Vous n'avez pas encore d'image pour ce joueur</p>
    <% end %>
  </div>

  <div class="field">
    <%= form.collection_select :role_id, Role.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.collection_select :club_id, Club.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.collection_select :nationality_id, Nationality.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Modifier Joueur</h1>

<%= render 'form', player: @player %>

<%= link_to 'Afficher', @player, class: 'btn btn-primary mr-3 mt-3' %>
<%= link_to 'Retour', players_path, class: 'btn btn-light mt-3' %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Les joueurs</h1>

<table class="table text-center">
  <thead>
    <tr>
      <th scope="col">Nom</th>
      <th scope="col">Vitesse</th>
      <th scope="col">Force</th>
      <th scope="col">Défense</th>
      <th scope="col">Tir</th>
      <th scope="col">Rareté</th>
      <th scope="col">Prix</th>
      <th scope="col" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.speed %></td>
        <td><%= player.strength %></td>
        <td><%= player.defense %></td>
        <td><%= player.shoot %></td>
        <td><%= player.rarity %></td>
        <td><%= player.price %></td>
        <td><%= link_to 'Afficher', player, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Modifier', edit_player_path(player), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Supprimer', player, method: :delete, data: { confirm: 'Êtes-vous sûr?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Player', new_player_path, class: 'btn btn-success mb-3 ml-3' %>

app/views/players/my_players.html.erb
<p id="notice"><%= notice %></p>

<h1>Vos joueurs</h1>

<ul>
  <% @players.each do |player| %>
  <li>
    <span><%= player.name %></span>
    <span><%= player.note %></span>
    <span><%= link_to 'Vendre', sell_player_path(player) %></span>
    <span><%= link_to 'Détails', player %></span>
  </li>
  <% end %>
</ul>

app/views/players/new.html.erb
<h1>Nouveau Joueur</h1>

<%= render 'form', player: @player %>

<%= link_to 'Retour', players_path, class: 'btn btn-light mt-3' %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Note générale</strong>
  <%= @player.note %>
</p>

<p>
  <strong>Vitesse:</strong>
  <%= @player.speed %>
</p>

<p>
  <strong>Force:</strong>
  <%= @player.strength %>
</p>

<p>
  <strong>Défense:</strong>
  <%= @player.defense %>
</p>

<p>
  <strong>Tir:</strong>
  <%= @player.shoot %>
</p>

<p>
  <strong>Rareté:</strong>
  <%= @player.rarity %>
</p>

<% if @player.avatar.attached? %>
  <p>
    <%= image_tag @player.avatar, width: "150", alt: @player.name %>
  </p>
<% end %>

<% if current_user.try(:admin?) %>
  <%= link_to 'Modifier', edit_player_path(@player), class: 'btn btn-warning mr-3' %>
<% end %>

<%= link_to 'Retour', my_players_path, class: 'btn btn-light' %>