config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  authenticate :user do
    get 'users/index'
    get 'users/match/:user_id' => 'users#match', as: :match
    resources :teams
    resources :nationalities
    resources :leagues
    resources :clubs
    resources :roles
    resources :players do
      get 'sell', on: :member
      get 'my/players', action: :my_players, as: :my, on: :collection
    end
    resources :packs do
      get 'list', on: :collection
      get ':user_id/buy', action: :buy, as: :buy, on: :member
    end
  end
end

app/models/nationality.rb
class Nationality < ApplicationRecord
  has_many :players
  has_one_attached :avatar
end

app/controllers/nationalities_controller.rb
class NationalitiesController < ApplicationController
  before_action :set_nationality, only: [:show, :edit, :update, :destroy]

  # GET /nationalities
  def index
    @nationalities = Nationality.all
  end

  # GET /nationalities/1
  def show
  end

  # GET /nationalities/new
  def new
    @nationality = Nationality.new
  end

  # GET /nationalities/1/edit
  def edit
  end

  # POST /nationalities
  def create
    @nationality = Nationality.new(nationality_params)

    respond_to do |format|
      if @nationality.save
        format.html { redirect_to @nationality, notice: 'Nationality was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /nationalities/1
  def update
    respond_to do |format|
      if @nationality.update(nationality_params)
        format.html { redirect_to @nationality, notice: 'Nationality was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /nationalities/1
  def destroy
    @nationality.destroy
    respond_to do |format|
      format.html { redirect_to nationalities_url, notice: 'Nationality was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nationality
      @nationality = Nationality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nationality_params
      params.require(:nationality).permit(:name, :logo, :avatar)
    end
end

app/helpers/nationalities_helper.rb
module NationalitiesHelper
end

app/views/nationalities/_form.html.erb
<%= form_with(model: nationality, local: true) do |form| %>
  <% if nationality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nationality.errors.count, "error") %> prohibited this nationality from being saved:</h2>

      <ul>
      <% nationality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nationalities/edit.html.erb
<h1>Modifier Nationalité</h1>

<%= render 'form', nationality: @nationality %>

<%= link_to 'Afficher', @nationality, class: 'btn btn-primary mr-3 mt-3' %>
<%= link_to 'Retour', nationalities_path, class: 'btn btn-light mt-3' %>

app/views/nationalities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Les nationalités</h1>

<table class="table text-center">
  <thead>
    <tr>
      <th scope="col">Nom</th>
      <th scope="col">Logo</th>
      <th scope="col" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @nationalities.each do |nationality| %>
      <tr>
        <td><%= nationality.name %></td>
        <td><%= image_tag nationality.avatar, width: "50", alt: nationality.name %></td>
        <td><%= link_to 'Afficher', nationality, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Modifier', edit_nationality_path(nationality), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Supprimer', nationality, method: :delete, data: { confirm: 'Êtes-vous sûr?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouvelle nationalité', new_nationality_path, class: 'btn btn-success mb-3 ml-3' %>

app/views/nationalities/new.html.erb
<h1>Nouvelle Nationalité</h1>

<%= render 'form', nationality: @nationality %>

<%= link_to 'Retour', nationalities_path, class: 'btn btn-light mt-3' %>

app/views/nationalities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @nationality.name %>
</p>

<p>
  <strong>Logo:</strong>
  <%= image_tag @nationality.avatar, width: "50", alt: @nationality.name %>
</p>

<%= link_to 'Modifier', edit_nationality_path(@nationality), class: 'btn btn-warning mr-3' %>
<%= link_to 'Retour', nationalities_path, class: 'btn btn-light' %>