config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  authenticate :user do
    get 'users/index'
    get 'users/match/:user_id' => 'users#match', as: :match
    resources :teams
    resources :nationalities
    resources :leagues
    resources :clubs
    resources :roles
    resources :players do
      get 'sell', on: :member
      get 'my/players', action: :my_players, as: :my, on: :collection
    end
    resources :packs do
      get 'list', on: :collection
      get ':user_id/buy', action: :buy, as: :buy, on: :member
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
  has_many :players
  belongs_to :league
  has_one_attached :avatar
end

app/models/league.rb
class League < ApplicationRecord
  has_many :clubs
  has_one_attached :avatar
end

app/models/nationality.rb
class Nationality < ApplicationRecord
  has_many :players
  has_one_attached :avatar
end

app/models/pack.rb
class Pack < ApplicationRecord
  has_and_belongs_to_many :players

  def buy(user)
    amount = user.credit - self.price
    if amount < 0
      return false
    end

    user.credit = amount
    user.save
  end

  def open
    available_players = self.players
    players_list = []
    for player in available_players do
      increment = 0
      while increment < (100 - player.rarity) do
        players_list.push(player.id)
        increment += 1
      end
    end
    players_list = players_list.shuffle

    pack_players = []
    increment = 0
    while increment < self.cards_number do
      pack_players.push(Player.find(players_list.sample))
      increment += 1
    end

    pack_players
  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_and_belongs_to_many :packs
  has_and_belongs_to_many :teams
  belongs_to :club
  belongs_to :nationality
  belongs_to :role
  has_one_attached :avatar

  def sell(user)
    # remove the player from association table
    sql = "DELETE FROM players_users WHERE user_id=#{user.id} AND player_id=#{self.id} LIMIT 1"
    ActiveRecord::Base.connection.execute(sql)

    user.credit = user.credit + self.price
    user.save
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :players
end

app/models/team.rb
class Team < ApplicationRecord
  has_and_belongs_to_many :players
  belongs_to :user
  validates :name, presence: { message: 'Le nom est obligatoire' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :players
  has_many :teams

  def after_database_authentication
    if self.last_connection.nil? || !self.last_connection.to_s.start_with?(Date.today.to_s)
      self.update_attributes(:last_connection => Date.today.to_s)
      self.credit += 1000
    end
  end

  def fight(user)
    success = rand(10) > rand(10)

    #TODO : calculate winner based on users active team players

    if success
      # attribute match reward in case of win
      self.credit = self.credit + 500
      self.save
    end
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /clubs/1
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /clubs/1
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name, :logo, :city, :league_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/packs_controller.rb
class PacksController < ApplicationController
  before_action :set_pack, only: [:show, :edit, :update, :destroy]

  # GET /packs
  def index
    @packs = Pack.all
  end

  def list
    @packs = Pack.all
    @isBuy = true

    render 'index'
  end

  def buy
    @pack = Pack.find(params[:id])
    @user = User.find(params[:user_id])
    success = @pack.buy(@user)
    if success
      @pack_players = @pack.open
      for player in @pack_players do
        @user.players << player
      end
    end

    respond_to do |format|
      if success
        format.html { render :buy, notice: 'La pack a bien été acheté.' }
      else
        format.html { redirect_to list_packs_path, notice: 'Vous ne pouvez pas acheter ce pack.' }
      end
    end
  end

  # GET /packs/1
  def show
    @pack = Pack.find(params[:id])
    @players = @pack.players

    respond_to do |format|
      format.html
    end
  end

  # GET /packs/new
  def new
    @pack = Pack.new
    @players = Player.all
  end

  # GET /packs/1/edit
  def edit
    @players = Player.all
  end

  # POST /packs
  def create
    @pack = Pack.new(pack_params)

    respond_to do |format|
      if @pack.save
        format.html { redirect_to @pack, notice: 'Pack was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /packs/1
  def update
    params[:pack][:player_ids] ||= []
    @pack = Pack.find(params[:id])

    respond_to do |format|
      if @pack.update(pack_params)
        format.html { redirect_to @pack, notice: 'Pack was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /packs/1
  def destroy
    @pack.destroy
    respond_to do |format|
      format.html { redirect_to packs_url, notice: 'Pack was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pack
      @pack = Pack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pack_params
      params.require(:pack).permit(:name, :price, :cards_number, :player_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/packs_helper.rb
module PacksHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hut</title>
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>
  <main class="page-<%= controller_name %>">

    <nav>
      <%= render "/nav/default.html.erb" %>
    </nav>
    <div class="container mt-3">
      <%= yield %>
    </div>
    <footer class="page-footer">
      <%= render "/partials/footer.html.erb" %>
    </footer>

  </main>
</body>
</html>

app/views/nav/_default.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">HUT</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item"><%= link_to 'Mes équipes', teams_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Mes joueurs', my_players_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Acheter des packs', list_packs_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Affronter des joueurs', users_index_path, class: 'nav-link' %></li>
      <% end %>

      <% if current_user.try(:admin?) %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Gestion
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Gérer les packs', packs_path, class: 'dropdown-item' %>
          <%= link_to 'Gérer les joueurs', players_path, class: 'dropdown-item' %>
          <%= link_to 'Gérer les nationalités', nationalities_path, class: 'dropdown-item' %>
          <%= link_to 'Gérer les championnats', leagues_path, class: 'dropdown-item' %>
          <%= link_to 'Gérer les clubs', clubs_path, class: 'dropdown-item' %>
          <%= link_to 'Gérer les postes sur le terrain', roles_path, class: 'dropdown-item' %>
        </div>
      </li>
      <% end %>
    </ul>

    <ul class="navbar-nav">
    <% if user_signed_in? %>
      <span class="nav-link float-right">Crédits : <%= current_user.credit %></span>
    <% end %>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Se connecter", new_user_session_path, class: 'nav-link' %>
      </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/partials/_footer.html.erb
<p>Copyright &copy; HUT - 2018 - VIE Yoann - BERTIN Louis - LOUIS Jérémy</p>